name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir /home/runner/work/VTFLib/build
      run: mkdir /home/runner/work/VTFLib/build && cd /home/runner/work/VTFLib/build && ls -lah /home/runner/work/VTFLib/
    - name: cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - name: make -j`nproc`
      run: make -j`nproc`
    - name: make install
      run: make install
